### ISSUE TITLE
Empty hourly dataPoints

### ISSUE THREAD

**Issue by chikamim** [mattnedrich/SwiftForecast#1]
The raw json has hourly data, but there is no hourly dataPoints in forecastInfo class.
I think dictionary cast failed in "DataBlock.swift". That dictionary type should be "String, AnyObject".

https://github.com/mattnedrich/SwiftForecast/blob/baacb0caa5947b9f4c49da6a15857af112f977fe/SwiftForecast/DataBlock.swift#L21,L23

**Comment by mattnedrich** [comment]
Thanks for reporting this, I'll look into it.

**Comment by mattnedrich** [comment]
@bradex should be fixed now
